<?php 
/*
Plugin Name: Contact Form 7 Extension
Plugin URI: https://sandipmistry.com
Description: Contact From 7 Extension with Design Features
Version: 0.0.1
Author: Sandip Mistry
Author URI: https://sandipmistry.com
Text Domain: cf7e
Generated By: http://ensuredomains.com
*/

// If this file is called directly, abort. //
if ( ! defined( 'WPINC' ) ) {die;} // end if

// Let's Initialize Everything
if ( file_exists( plugin_dir_path( __FILE__ ) . 'core-init.php' ) ) {
require_once( plugin_dir_path( __FILE__ ) . 'core-init.php' );
}